version: 2.1
workflows:
  workflow1:
    jobs:
      - database1
jobs:
  database1:
    docker:
      - image: circleci/node:12
        environment:
          DATABASE_URL: postgres://psqluer:psqlpassword@localhost:5432/psdb
          JWT_SECRET: some string yo want
          API_PORT: 3000
          API_HOST: localhost
          API_PROTOCOL: http
      - image: circleci/postgres
        environment:
          POSTGRES_USER: psqluer
          POSTGRES_PASSWORD: psqlpassword
          POSTGRES_DB: psdb
    
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn test:e2e
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lcok" }}
          paths:
            - ./node_modules